source 'https://github.com/tobefine/Company_index1.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ComMain_Example' do
  pod 'ComMain', :path => '../'

  target 'ComMain_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
